@host=http://localhost:5112
@adminId=211b672c-e0f5-45c3-aaef-b4a9bcbd5545

POST {{host}}/subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free",
    "AdminId": "{{adminId}}"
}

# {
#     "Id": "{{adminId}}"
#     "SubscriptionType": "Free", // "Starter", "Pro"
# }